version: "3.8"
services:
  atcoder:
    build:
      context: ./
      dockerfile: Dockerfile.ubuntu
    image: yukin01/atcoder:0.0.1
    container_name: atcoder
    tty: true
    volumes:
      - ./:/atcoder:cached
    working_dir: /atcoder
